### ISSUE TITLE
Electrs not indexing, stuck in fail/restart cycle.  

### ISSUE THREAD

**Issue by uskrusader** [raspibolt/raspibolt#887]
### Describe the issue
Electrs not indexing, it is stuck in a fail/restart cycle, repeating over and over gain.

### Location in guide
[Link to the corresponding page and section on <https://raspibolt.org>](https://raspibolt.org/electrs.html#autostart-on-boot)
$ sudo journalctl -f -u electrs   
(its been running for hours, but now constantly failing/restarting.

### Screenshots
![electrsnotindexing](https://user-images.githubusercontent.com/77032141/150710736-c804166e-1681-46c8-8d4a-a163ed019884.png)

### Environment
 - Hardware platform: Raspberry Pi 4
 - Operating system: Raspberry Pi OS 64bit, Debian 11

### Additional context

I'm not sure what to do next?!

**Comment by VajraOfIndra** [comment]
It looks like your "electrs" user does not have the permission to read the Bitcoin Core `.cookie` file.

Could you paste the output of the following command (with user "admin"):
`$ sudo ls -la /data/bitcoin`

And also the output of:
`$ groups electrs`

(The first command will tell if your `.cookie` file exists and is readable by members of the group "bitcoin", while the second command will tell if the "electrs" user is part of the "bitcoin" group.)

**Comment by uskrusader** [comment]
![electrscookie](https://user-images.githubusercontent.com/77032141/150852389-758efec1-67d8-4f31-b9ff-5d1d46fba56c.png)


uh-oh!  I don't see a cookie file, did I miss a step? ...or do a step in the wrong folder/directory? 
Thanks for helping me with this

**Comment by uskrusader** [comment]
![electrsconf](https://user-images.githubusercontent.com/77032141/150853782-124263fc-d3c9-400b-bd90-4667711943ee.png)

I redid previous steps, not sure if this helps...

**Comment by VajraOfIndra** [comment]
> ![electrscookie](https://user-images.githubusercontent.com/77032141/150852389-758efec1-67d8-4f31-b9ff-5d1d46fba56c.png)
> 
> uh-oh! I don't see a cookie file, did I miss a step? ...or do a step in the wrong folder/directory? Thanks for helping me with this

Ok so your "electrs" user is part of the "bitcoin" group, so that's great.

But you are missing the `.cookie` file indeed. Also, you have a symlink in `/data/bitcoin ` which should not be there. @ericsupreme in #884 has the same issue.. so I'm starting to wonder if there is a wording issue somewhere in the guide that leads to this. @Stadicus, any thoughts on this recurring issue?

In your `bitcoin.conf` file (open it with `sudo nano /home/bitcoin/.bitcoin/bitcoin.conf`), in the "# Connections" section, do you have the following line (but with the `raspibolt:01234....abcd` replaced by your own string generated by the Python script):
`rpcauth=raspibolt:01234....abcd`

Did you use the guide's template ([here](https://raspibolt.org/bitcoin-core.html#configuration)) to create your `bitcoin.conf` file?

**Comment by uskrusader** [comment]
I followed the guide, but I did have a couple of connection interruptions....

![rpcauth](https://user-images.githubusercontent.com/77032141/151184773-9e9cd6e4-40fc-4601-b826-a86696634a35.png)

**Comment by uskrusader** [comment]
...just redid and noticed this:

![chmod640](https://user-images.githubusercontent.com/77032141/151191686-3449dc20-d461-46b3-9d2f-e235e954181f.png)

**Comment by VajraOfIndra** [comment]
> I followed the guide, but I did have a couple of connection interruptions.... Does this look right?
> 
> (aside from the 2 added (#) to reduce 'dbcache' after full sync))

Yes, the conf file looks good.

**Comment by VajraOfIndra** [comment]
> ...just redid this step and noticed this:

That's because you're trying to change the permissions with your "admin" user who does not have the rights to do this file.

Either use the same command with your "bitcoin" user, as is done in the guide (or else with user "admin" try using adding `sudo` in front of the command, it should work as well).

Once you've done that, start bitcoind again (or restart it if it's already running as a background service) and check if the cookie file has been created.

**Comment by uskrusader** [comment]
feeling dumb here.... so what exactly is the command to restart (or reindex)

![bitcoind](https://user-images.githubusercontent.com/77032141/151198280-7d201ac4-9381-45af-bc86-8648920cb125.png)

**Comment by uskrusader** [comment]
it looks like it running in the background, yes?

![bitcoindrunning](https://user-images.githubusercontent.com/77032141/151199373-8a57dcc1-61aa-4eb7-82a1-66fa32e493ff.png)

**Comment by VajraOfIndra** [comment]
The errors in the logs could be due to launching bitcoind while it's already running in the background... but that's just an uninformed guess...

If `bitcoind` is running in the background (as it seems to be), that's what I would do:
* Restart bitcoind by issuing the following command (with the "admin" user): `sudo systemctl restart bitcoind`
* Wait a few minutes
* Check the logs by issuying the following command: `sudo tail -f /data/bitcoin/debug.log`
  * do the logs look ok? do they contain error messages?
* If the logs look ok, check that the `.cookie` file has been created by checking the content of the Bitcoin folder: `sudo ls -la /data/bitcoin`

**Comment by uskrusader** [comment]
Looks like errors....  it seems to continuous retry until I CTRL-C

![27jan22error1](https://user-images.githubusercontent.com/77032141/151388334-a3a0b3ca-8d78-4e2b-b4e2-d1cfebb1baa8.png)

**Comment by VajraOfIndra** [comment]
> Looks like errors.... it seems to continuous retry until I CTRL-C
> 
> "Please restart with -reindex or -reindex-chainstate to recover" (I'm not sure what the command line input would be for that if it is required)

I never encountered this issue before so I hope someone else might help you better than me.. but this is what I would try (there might be a better/quicker way, I'm just telling you how I'd do it with the little I know :). Basically I'd stop and disbale the service and start Bitcoin Core manually since I know I can add a flag to the command, so:
```
$ sudo systemctl stop bitcoind
$ sudo systemctl disable bitcoind
$ sudo su - bitcoin
$ bitcoind -reindex-chainstate
```
Wait for the reindexing to be completed and see if bitcoind then runs fine:
* if yes, proceed to check if the `.cookie` file exists as described above
* if not, stop bitcoind (Ctrl+C) and start it again but this time with the -reindex flag (it will take longer)
  *  `bitcoind -reindex`

Once you're finished (if all works well), make sure you stop bitcoin (Ctrl+C) and then enable and start the service again:
```
$ sudo systemctl enable bitcoind
$ sudo systemctl start bitcoind
```

I hope someone else might be able to shed some light on your issues though.

**Comment by uskrusader** [comment]
![Screenshot (14)](https://user-images.githubusercontent.com/77032141/152596337-5a224d5c-4c31-4706-abb3-6df7dca5842a.png)

Am I good to go here?  Is my Electrs fully indexed?

**Comment by VajraOfIndra** [comment]
> Am I good to go here? Is my Electrs fully indexed?

Looks good to me! I have the same kind of outputs in my logs and my Electr is fully indexed.

**Comment by VajraOfIndra** [comment]
Can we close this issue? :)

**Comment by uskrusader** [comment]
close it!  ....
