### ISSUE TITLE
[FEATURE REQ]  update your rsync command to include maintaining owner and group

### ISSUE THREAD

**Issue by visskiss** [raspibolt/raspibolt#933]
### What & why

When following [this guide for transferring data from an on old install](https://raspibolt.org/faq.html#can-i-update-my-raspibolt-2-to-the-new-version), you use the rsync command with the flags 

-rhvP

You should update this to use the flags

-rhvPog

So that owner and group are maintained as well as permissions. 

Either that or you need to add the commands to update owner and group, ie

chown -r bitcoin:bitcoin /data/bitcoin

etc.

**Comment by VajraOfIndra** [comment]
Good idea! 

`-ahvP` could work as well and preserve modification times (but it works without preserving them so it does not add much)

This would work great for copying over the Bitcoin data and avoid having to do a `chown` command.   
However, for copying over the LND data, we would still need to use `sudo chown -r lnd:lnd /data/lnd` since the LND data folder owner/group has changed from "bitcoin" (in v2) to "lnd" (in v3).

**Comment by VajraOfIndra** [comment]
@visskiss See PR #935 Could you leave a review?
