### ISSUE TITLE
simple problem?

### ISSUE THREAD

**Issue by uskrusader** [raspibolt/raspibolt#947]
### Describe the issue
A clear and concise description of where you're stuck in the guide. What are you trying to do, and how is it not working?
So I ran the guide all the way to the end of "Bitcoin/Electrum server" section.  My electrum wallet will not connect to my node.  So I went back through a bunch of steps in "Bitcoin Client" section.  When I try to see "Bitcoind" in action, I get an "permission denied" error.  It seems to work if I put "sudo" in front of "tail -f /home/bitcoin/.bitcoin/debug.log"   

Did I do something wrong?  or did the guide miss the "sudo" command?

Also should this require the password for "admin" to continue?  it seems to work, but the guide doesn't mention using "sudo" or needing to enter your admin password.

### Location in guide
Raspibolt Guide: Bitcoin/Bitcoin Client

Link to the corresponding page and section on <https://raspibolt.org>
https://raspibolt.org/guide/bitcoin/bitcoin-client.html#verification-of-bitcoind-operations

### Environment
 - Hardware platform: Raspberry Pi 4
 Raspberry Pi OS 64bit, Debian 11, ... ]

**Comment by Stadicus** [comment]
Hi there, the `sudo` command should not be necessary for user "admin" to have read-only access to the Bitcoin directory. this sounds like a permission problem.

Could you run the following command and see what your system says in regards to the highlighted part?

![image](https://user-images.githubusercontent.com/19550140/156516580-0bd2fba1-88fd-4b93-a95b-409f069b0b90.png)

If you get an error, maybe you need to run `sudo ls -la /data/bitcoin` due to the same issue.

**Comment by uskrusader** [comment]
Mine looks a little different...  
![3mar22](https://user-images.githubusercontent.com/77032141/156592827-61bfcec1-2fd6-45cc-a834-263aa786c710.png)

**Comment by RooSoft** [comment]
Use the `bitcoin` user and you won't need to sudo...

Also, your `admin` user probably isn't in the `bitcoin` group... would be an even simpler fix.

```bash
sudo adduser admin bitcoin
```

And then you'll be able to tail the file directly with `admin`.

**Comment by uskrusader** [comment]
Looks like i already added admin to bitcoin group (?)
...but still doesnt work without sudo 
![3mar22b](https://user-images.githubusercontent.com/77032141/156603421-4178cc0b-5c78-40e9-b61a-f7c436192b22.png)

**Comment by VajraOfIndra** [comment]
**OOT:** @Stadicus, I see that your `debug.log` can also be read by "other"/any users... same with mine. Is that expected knowing that we grant access only to the group users with `chmod g+r /data/bitcoin/debug.log`...?

I would expect the file permissions to be:
`-rw-r-----`
and not:
`-rw-r--r--`

What am I missing there?

**Comment by Stadicus** [comment]
> What am I missing there?

Probably nothing, the file does not need to be readable by anyone. My system is a mess... :)

**Comment by VajraOfIndra** [comment]
> > What am I missing there?
> 
> Probably nothing, the file does not need to be readable by anyone. My system is a mess... :)

so is mine then :laughing: I also have -rw-r--r--

**Comment by RooSoft** [comment]
Yeah.. that's definitely a `chmod` job... totally missed this detail.

**Comment by uskrusader** [comment]
![3mar22c](https://user-images.githubusercontent.com/77032141/156637169-aa21920f-4b7b-4e0d-b2bd-6b48232078a6.png)

> Your `debug.log` file can only be read by the "bitcoin" user right now. You probably missed this step: ![image](https://user-images.githubusercontent.com/86242283/156613022-52fe9685-f8c9-4b3a-9580-9f9f35fd186c.png)
> 
> Log in with user "bitcoin" and run the above command: `chmod g+r /data/bitcoin/debug.log`
> 
> Then, any members of the group "bitcoin" (e.g. the "admin" user) will be able to read the log.

So I ran the command above twice.  I wasn't sure if /home/admin mattered. (see pic above)
that seemed to work.

I see lots of failures when i run the original tail command: tail -f /home/bitcoin/.bitcoin/debug.log
Is that normal?

So far, my electrum wallet is connected to my raspibolt node through TOR, (1 connection) I have the blue button.  I can't seem to connect it without TOR. I have received to and sent from a small amount of bitcoin to it to test it, success. But I'm still having issues connecting it to the BTC RPC explorer with or without TOR.  I started this project with ZERO knowledge. I feel so close to the end, but I'm still plagued with these little issues.  Thanks for your all your help.

**Comment by VajraOfIndra** [comment]
> So I ran the command above twice. I wasn't sure if /home/admin mattered. (see pic above) that seemed to work.

Being in /home/admin did not matter because you provided the full (absolute) path: `/data/bitcoin/debug.log` 
If you had provided only the log name `debug.log` for example, you would have needed to move into `/data/bitcoin` first with `cd /data/bitcoin`
 
> I see lots of failures when i run the original tail command: tail -f /home/bitcoin/.bitcoin/debug.log Is that normal?

It seems a common issue yes. See #914 for example. Nothing to worry about for now afaik.

> So far, my electrum wallet is connected to my raspibolt node through TOR, (1 connection) I have the blue button. I can't seem to connect it without TOR. I have received to and sent from a small amount of bitcoin to it to test it, success. But I'm still having issues connecting it to the BTC RPC explorer with or without TOR. I started this project with ZERO knowledge. I feel so close to the end, but I'm still plagued with these little issues. Thanks for your all your help.

Networking issues are very common yes. I suggest you close this issue and open new ones for each of your specific issue (one for your Electrum wallet connection issue and one for your BTC RPC Explorer local connection issue). 

Before opening these 2 new issues, if you didn't do it yet, maybe do a search in the repository for old issues with similar topics, you might find some helpful answers in older threads! But if not, just open new issues with the required information and you'll quickly get some help :)
