### ISSUE TITLE
Is “/mnt/static-channel-backup-external” listed?  nope 8-(

### ISSUE THREAD

**Issue by uskrusader** [raspibolt/raspibolt#958]
Lightning/Channel Backup/Option 1: Local Backup/Set up a mounting point for the storage device

$ sudo mkdir /mnt/static-channel-backup-external
$ sudo chattr +i /mnt/static-channel-backup-external

done

![8marchprob!](https://user-images.githubusercontent.com/77032141/157337942-d580a90c-5fce-4ed5-930f-5dc1a6f304f0.png)

![8marprob2](https://user-images.githubusercontent.com/77032141/157337985-59a89a4f-8a4f-400f-8a3f-56caffc80054.png)

I ran through this part of the guide twice, 
updated the /etc/fstab twice

Is “/mnt/static-channel-backup-external” listed?  
nope "...no such file or directory"
 
Any idea why it isnt listed?

in the meantime, I'll try using the remote github repositry method to backup.
cheers,

### Environment
 - Hardware platform: [e.g. Raspberry Pi 4, 
 - Operating system: [e.g, Raspberry Pi OS 64bit, Debian 11, ... ]

**Comment by uskrusader** [comment]
![8mar22directory](https://user-images.githubusercontent.com/77032141/157368626-524f1357-b1f6-4432-9d53-c1f19e42ca15.png)

**Comment by VajraOfIndra** [comment]
> ![8mar22directory](https://user-images.githubusercontent.com/77032141/157368626-524f1357-b1f6-4432-9d53-c1f19e42ca15.png)

Ibelieve it's because the folder was created at: `/mnt/static-channel-backup-external`

You invoke `df` from the root folder of user "admin" (`/home/admin`) and you provide a relative path, therefore it's trying to find the folder at: `/home/admin/static-channel-backup-external` (which does not exist)

Instead, you need to either provide the absolute path: `df -h /mnt/static-channel-backup-external`
Or else, you need to move to the parent folder of the targeted folder first before using the relative path:
```
cd /mnt
df -h static-channel-backup-external
```
